# Campaign Stack - AI Policy Chatbot Module (Optional)
# This is an add-on compose file for the chatbot module
# Usage: docker compose -f compose.yaml -f compose-chatbot.yaml up -d

services:

  # ============================================================================
  # CHATBOT DATABASE: Dedicated database for chatbot conversations and analytics
  # ============================================================================
  chatbot_db:
    image: mysql:8.0
    container_name: chatbot_db
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${CHATBOT_DB_ROOT_PASSWORD:-chatbotroot123}
      MYSQL_DATABASE: chatbot
      MYSQL_USER: chatbot
      MYSQL_PASSWORD: ${CHATBOT_DB_PASSWORD:-chatbotsecure123}
    volumes:
      - chatbot_db_data:/var/lib/mysql
      - ./chatbot-module/db/init.sql:/docker-entrypoint-initdb.d/01-chatbot-schema.sql
    networks:
      - traefik
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ============================================================================
  # AI ROUTER: Multi-backend AI routing service
  # ============================================================================
  ai_router:
    build:
      context: ./chatbot-module/ai-router
      dockerfile: Dockerfile
    container_name: ai_router
    depends_on:
      chatbot_db:
        condition: service_healthy
    environment:
      # Database
      CHATBOT_DB_HOST: chatbot_db
      CHATBOT_DB_NAME: chatbot
      CHATBOT_DB_USER: chatbot
      CHATBOT_DB_PASSWORD: ${CHATBOT_DB_PASSWORD:-chatbotsecure123}

      # AI Backends
      CHATBOT_DEFAULT_BACKEND: ${CHATBOT_DEFAULT_BACKEND:-ollama}
      OLLAMA_HOST: ${OLLAMA_HOST:-http://ai_provider:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-llama2}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      ANTHROPIC_MODEL: ${ANTHROPIC_MODEL:-claude-3-haiku-20240307}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      GOOGLE_MODEL: ${GOOGLE_MODEL:-gemini-pro}

      # Budget Controls
      CHATBOT_MONTHLY_BUDGET: ${CHATBOT_MONTHLY_BUDGET:-100}
      CHATBOT_ANTHROPIC_BUDGET: ${CHATBOT_ANTHROPIC_BUDGET:-50}
      CHATBOT_OPENAI_BUDGET: ${CHATBOT_OPENAI_BUDGET:-30}
      CHATBOT_GOOGLE_BUDGET: ${CHATBOT_GOOGLE_BUDGET:-20}

      # Routing Thresholds
      CHATBOT_SIMPLE_TOKENS: ${CHATBOT_SIMPLE_TOKENS:-50}
      CHATBOT_COMPLEX_TOKENS: ${CHATBOT_COMPLEX_TOKENS:-200}

      # Privacy
      CHATBOT_REQUIRE_CONSENT: ${CHATBOT_REQUIRE_CONSENT:-true}
      CHATBOT_ANONYMIZE_DATA: ${CHATBOT_ANONYMIZE_DATA:-true}

      # API Port
      CHATBOT_API_PORT: 5001
    volumes:
      - chatbot_router_data:/app/data
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-api.rule=Host(`chatbot-api.${BACKEND_DOMAIN:-${DOMAIN}}`)"
      - "traefik.http.routers.chatbot-api.entrypoints=web,websecure"
      - "traefik.http.routers.chatbot-api.tls=true"
      - "traefik.http.routers.chatbot-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.chatbot-api.loadbalancer.server.port=5001"

  # ============================================================================
  # WIKI.JS CONNECTOR: Fetches and caches policy content from Wiki.js
  # ============================================================================
  wikijs_connector:
    build:
      context: ./chatbot-module/wikijs-connector
      dockerfile: Dockerfile
    container_name: wikijs_connector
    depends_on:
      chatbot_db:
        condition: service_healthy
      wiki:
        condition: service_started
    environment:
      # Wiki.js
      WIKIJS_URL: http://wiki:3000
      WIKIJS_API_KEY: ${WIKIJS_API_KEY:-}

      # Database
      CHATBOT_DB_HOST: chatbot_db
      CHATBOT_DB_NAME: chatbot
      CHATBOT_DB_USER: chatbot
      CHATBOT_DB_PASSWORD: ${CHATBOT_DB_PASSWORD:-chatbotsecure123}

      # Cache settings
      WIKIJS_CACHE_TTL_HOURS: ${WIKIJS_CACHE_TTL_HOURS:-24}
      WIKIJS_CONNECTOR_PORT: 5002
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wikijs-connector.rule=Host(`wikijs-connector.${BACKEND_DOMAIN:-${DOMAIN}}`)"
      - "traefik.http.routers.wikijs-connector.entrypoints=web,websecure"
      - "traefik.http.routers.wikijs-connector.tls=true"
      - "traefik.http.routers.wikijs-connector.tls.certresolver=letsencrypt"
      - "traefik.http.services.wikijs-connector.loadbalancer.server.port=5002"

# ================================================================================
# VOLUMES: Persistent data for chatbot module
# ================================================================================
volumes:
  chatbot_db_data:
  chatbot_router_data:

# Note: Networks are defined in main compose.yaml
