# Campaign Stack - ACBC Voter Intelligence Module (Optional)
# This is an add-on compose file for the ACBC module
# Usage: docker compose -f compose.yaml -f compose-acbc.yaml up -d

services:

  # ============================================================================
  # LIMESURVEY: Survey engine for ACBC data collection
  # ============================================================================
  limesurvey:
    image: martialblog/limesurvey:6-apache
    container_name: limesurvey
    depends_on:
      acbc_db:
        condition: service_healthy
    environment:
      DB_TYPE: mysql
      DB_HOST: acbc_db
      DB_PORT: 3306
      DB_NAME: limesurvey
      DB_USERNAME: limesurvey
      DB_PASSWORD: ${LIMESURVEY_DB_PASSWORD:-limesecure123}
      ADMIN_USER: admin
      ADMIN_PASSWORD: ${LIMESURVEY_ADMIN_PASSWORD:-ChangeMeNow123!}
      ADMIN_NAME: Survey Admin
      ADMIN_EMAIL: ${LETSENCRYPT_EMAIL}
      PUBLIC_URL: https://survey.${DOMAIN}
    volumes:
      - limesurvey_data:/var/www/html/upload
      - limesurvey_plugins:/var/www/html/plugins
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.limesurvey.rule=Host(`survey.${DOMAIN}`)"
      - "traefik.http.routers.limesurvey.entrypoints=web,websecure"
      - "traefik.http.routers.limesurvey.tls=true"
      - "traefik.http.routers.limesurvey.tls.certresolver=letsencrypt"
      - "traefik.http.services.limesurvey.loadbalancer.server.port=80"

  # ============================================================================
  # ACBC Database: Separate database for ACBC analytics
  # ============================================================================
  acbc_db:
    image: mysql:8.0
    container_name: acbc_db
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${ACBC_DB_ROOT_PASSWORD:-acbcsecure123}
      MYSQL_DATABASE: limesurvey
      MYSQL_USER: limesurvey
      MYSQL_PASSWORD: ${LIMESURVEY_DB_PASSWORD:-limesecure123}
    volumes:
      - acbc_db_data:/var/lib/mysql
      - ./acbc-module/db/init.sql:/docker-entrypoint-initdb.d/01-acbc-schema.sql
    networks:
      - traefik
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ============================================================================
  # ACBC Analytics Engine: Python service for utility calculations
  # ============================================================================
  acbc_analytics:
    build:
      context: ./acbc-module/analytics-engine
      dockerfile: Dockerfile
    container_name: acbc_analytics
    depends_on:
      acbc_db:
        condition: service_healthy
      wordpress_mysql:
        condition: service_healthy
    environment:
      ACBC_DB_HOST: acbc_db
      ACBC_DB_NAME: limesurvey
      ACBC_DB_USER: limesurvey
      ACBC_DB_PASSWORD: ${LIMESURVEY_DB_PASSWORD:-limesecure123}
      CIVICRM_DB_HOST: wordpress_mysql
      CIVICRM_DB_NAME: ${MYSQL_DATABASE}
      CIVICRM_DB_USER: ${MYSQL_USER}
      CIVICRM_DB_PASSWORD: ${MYSQL_PASSWORD}
      API_PORT: 5000
    volumes:
      - acbc_analytics_data:/app/data
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.acbc-api.rule=Host(`acbc-api.${DOMAIN}`)"
      - "traefik.http.routers.acbc-api.entrypoints=web,websecure"
      - "traefik.http.routers.acbc-api.tls=true"
      - "traefik.http.routers.acbc-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.acbc-api.loadbalancer.server.port=5000"

  # ============================================================================
  # ACBC Dashboard: Admin interface for monitoring and analytics
  # ============================================================================
  acbc_dashboard:
    build:
      context: ./acbc-module/admin-dashboard
      dockerfile: Dockerfile
    container_name: acbc_dashboard
    depends_on:
      - acbc_analytics
    environment:
      ANALYTICS_API_URL: http://acbc_analytics:5000
      DASHBOARD_PORT: 3001
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.acbc-dashboard.rule=Host(`acbc.${DOMAIN}`)"
      - "traefik.http.routers.acbc-dashboard.entrypoints=web,websecure"
      - "traefik.http.routers.acbc-dashboard.tls=true"
      - "traefik.http.routers.acbc-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.acbc-dashboard.loadbalancer.server.port=3001"

# ================================================================================
# VOLUMES: Persistent data for ACBC module
# ================================================================================
volumes:
  limesurvey_data:
  limesurvey_plugins:
  acbc_db_data:
  acbc_analytics_data:

# Note: Networks are defined in main compose.yaml
